mailgun/mailgun-ruby

README.md, lib/mailgun/client.rb, lib/mailgun/response.rb, lib/mailgun/version.rb, spec/integration/mailgun_spec.rb, spec/unit/mailgun_spec.rb
Super basic implementation of a "test mode" allowing users to easily stub calls that send emails.
Initially, it is just for stubbing the message sending routine, but can be expanded to stub other API calls if necessary.
Test mode is also tested. :joy:
*EDIT*: Version has also been bumped to 1.1.2 for this feature.
=> Test mode implementation, #24

Snippets.md
The leading newline on the MIME string prevents it from being processed correctly by the API. Thanks @clhammer :)
=> Remove leading newline from MIME string.

README.md
This is especially useful for non-Rails app. It reduces guesswork (e.g. require 'mailgun-ruby' or 'mailgun'?), and would accelerate time to create a working version.
=> Document what to require

lib/mailgun-ruby.rb, lib/railgun.rb, lib/railgun/mailer.rb, lib/railgun/railtie.rb
This will automatically load the railgun ActionMailer delivery method when Rails is present. It also switches to a Railtie so it will be added at the right point (when ActionMailer is loaded, but before any config is done to avoid missing method errors).
Fixes #80
=> Autoload Railgun in Rails

lib/railgun/mailer.rb
The previous code was throwing this error:
> Undefined method ConfigurationError
This change fixes the `raise` syntax to work with this custom exception.
=> Fix raise syntax for custom exceptions.

README.md, lib/mailgun/client.rb
Fixes #93 
Also documents `Mailgun::Client#enable_test_mode!`, which was undocumented.
=> Store mail deliveries in test mode

lib/mailgun/messages/message_builder.rb, spec/unit/messages/message_builder_spec.rb
We needed List-Unsubscribe header to improve deliverability.
We're using it in a batch_message with custom variables since each link is unique by user.
=> add list_unsubcribe method

lib/mailgun/events/events.rb
Ideas:
+ Maybe `get` should just be an alias for `next`?
+ Make `params` and argument to initialize. This will allow you to make the Events object enumerable.
```ruby
class Events
include Enumerable
def each(&block)
items = self.next.to_h['items']
until items.empty?
items.each(&block)
items = self.next.to_h['items']
end
end
end
```
=> Events#previous and Events#next should accept params

README.md
Added example to README of how to get the message_id returned from the Mailgun api after sending an email using Rails/ActionMailer.
=> Additional README Rails/ActionMailer example

lib/mailgun/address.rb, spec/integration/email_validation_spec.rb, vcr_cassettes/email_validation.yml
Allow mailbox verification when validating addresses by sending the `mailbox_verification` query string param [per the documentation](https://documentation.mailgun.com/en/latest/api-email-validation.html#email-validation).
=> Perform mailbox validation

lib/railgun/mailer.rb, mailgun.gemspec, spec/unit/railgun_spec.rb
Hello, let me submit PR as per the suggestion made at #130.
Tweaked current Railgun's module_functions so that it does *not* overwrite the email body when nothing is given.
* related with #130 #106 #128 
* (may have crossed with old PR as well)
Also added a decent unit test to highlight the original issue:
When running with the current master, Railgun renders html and text part regardless its original settings.
WIth the branch you should see the test goes all green! (which is how ActionMailer behaves by default)
* When updated, it stops creating multipart emails when you don't have the both templates in place. 
* Another small thing: in order to run railgun on rails, I had to add rails gem (for development environment only).
Hopefully it makes sense (esp. if you are going to add some …
=> Fix content type

lib/mailgun/messages/message_builder.rb, spec/unit/messages/message_builder_spec.rb
In some places in our code base we store senders/recipients with their full name instead of first/last.
Also, seems like it could be useful in cases where sender or recipients don't have first/last names (e.g. sending on behalf of a team).
=> Small/easy to review PR: Allow caller to specify full_name instead of first/last.

docs/Webhooks.md
This PR fixes a minor typo in `Webhooks.md` file where remove_all was incorrectly mentioned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mailgun/mailgun-ruby/115)
=> [Docs] fixed Webhooks.md `remove_all` method in docs.

lib/mailgun/webhooks/webhooks.rb
Use `'message'` instead of `message`.
=> Fix error in Webhooks create method

lib/mailgun/events/events.rb, spec/unit/events/events_spec.rb
As discussed in #124 pagination has been broken as @manuelmeurer pointed out the mistake was introduced in the commit here: https://github.com/mailgun/mailgun-ruby/commit/9ad5cbd95f2570b3a3c681cc1e362c702b84eded#diff-e904dd8e3437a9a9c5e35c6dcb227d30 by @fursich and @pirogoeth.
The method  `#extract_endpoint_from` processes a regex with a path as input, but the regex expects a url, thus the method will always be returning `nil`, and pagination is broken.
This means the Ruby-gem might have been broken since 16 Jun 2017.
My specs are a bit ugly, but I was in a hurry, please fix, or give me input how to fix them.
Go to an account with event-activity, modify the `begin`+`end` variables and run the following:
```ruby
require 'csv'
require 'mailgun'
require 'digest'
event_settings = {
'begin' => …
```
=> Fix pagination problem in Mailgun::Events-api introduced in v1.1.8

README.md
I struggled for about an hour before realising my domain was configured in `eu`. This extra info in the readme should help others.
NB. This pull request should also close https://github.com/mailgun/mailgun-ruby/pull/163
=> Include config info in README for EU domains

lib/mailgun/client.rb
If we pass a `timeout: nil` parameter to `RestClient::Resource.new`, that indicates no timeout. (Wait forever.)
Instead, rely on the default timeout if no timeout is specified.
fixes mailgun/mailgun-ruby#183
=> Depend on the RestClient default timeout for network timeouts

mailgun.gemspec
Fix https://github.com/mailgun/mailgun-ruby/issues/176
=> Relax version constraint on rest-client

lib/railgun/mailer.rb
There's currently no option to pass the `timeout` value to RestClient through Rails. This PR exposes `timeout` as a config value that could be added through action mailer settings, e.g:
```
config.action_mailer.mailgun_settings = {
timeout: 2
}
```
=> Allow timeout to be passed as a config option

lib/mailgun/suppressions.rb, spec/integration/suppressions_spec.rb, vcr_cassettes/suppressions.yml
I ran into the same error as AJMiller and wanted to submit a fix
The error in issue #150 is because when pulling a list of all unsubscribed, the `tag` key has an array value, so when the `create_unsubscribes` was calling `to_s` on any value that wasn't a string, it was doing so to an array, which was resulting in invalid JSON.
Rather than doing away with the entire block that converts to string, I added a condition checking for array, as it appears from the Mailgun docs that it can be either a singular string, in which case they give the key `tag`, or it can be an array, in which case they give the key `tags`.
See [Viewing a Single Unsubscribe](https://documentation.mailgun.com/en/latest/api-suppressions.html#view-a-single-unsubscribe) and [Add Multiple …
=> Fixes batch adding unsubscribes (Issue #150)

lib/mailgun.rb
The latest version (1.2.7) of the gem is broken.
This PR: https://github.com/mailgun/mailgun-ruby/pull/262 makes calls to `Mailgun.api_host` and `Mailgun.proxy_url` but the accessors were never added.
I can't find that there are any tests for this code, so I didn't add any in this PR either. I don't really understand how the tests are structured to be honest :) But, it's a pretty bad sign when bugs like this does not break the test suite and makes it out all the way in a new gem version.
Fixes: https://github.com/mailgun/mailgun-ruby/issues/273
=> Add missing accessors

lib/mailgun/exceptions/exceptions.rb, spec/unit/exceptions/exceptions_spec.rb
Fixes #295 
Currently, the body of 401 Mailgun's API responses doesn't include a `message` property. Instead, an `Error` (case-sensitive) property has the error message:
```json
{"Error":"unauthorized"}
```
This causes the current implementation of this gem to raise a runtime error instead of a `Mailgun::CommunicationError`, as expected.
This PR:
- Adds a workaround to avoid a runtime error from being raised
- Uses the `Error` property (if present) to compute the error's message
- Adds a unit test to verify this behavior
```shell
curl -i -X GET \
'https://api.mailgun.net/v3/foobar.com/events' \
-H 'Authorization: chuchublabla'
HTTP/2 401
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: no-store
content-type: application/json
date: Tue, 24 Sep 2024 …
```
=> Work around error responses without `message` property

mailgun.gemspec
The gem attempts to load the `mime/types` library during runtime, but the `mime-types` gem is currently listed as a development dependency in the `gemspec`. As a result, the gem is not available in production where only runtime dependencies are installed.
This leads to the following error when running the application:
```ruby
cannot load such file -- mime/types (LoadError)
```
This pull request changes the `mime-types` dependency from a **development** to a **runtime** dependency in the `gemspec`, ensuring that `mime-types` is included in all environments where the gem is used.
Fixes #333
=> Fix: Change mime-types to runtime dependency

lib/mailgun/messages/message_builder.rb, spec/unit/messages/message_builder_spec.rb
Fixes #349
This PR allows for filenames to be set on email attachements.
While #347 ensured that the file name was set on the IO object, it does not set it on the containing `UploadIO` object. So the filename is not set in the email attachment. This PR changes that.
`Faraday::Multipart::FilePart` is actually a `::Multipart::Post::UploadIO` object as can be seen here: https://github.com/lostisland/faraday-multipart/blob/main/lib/faraday/multipart/file_part.rb#L55
This class can take an optional filename as seen here https://rubydoc.info/gems/multipart-post/2.0.0/UploadIO:initialize, it is set to `nil` as default so there is no harm passing a `nil` filename if that is ever passed from `#add_file`. As such, this PR allows for `nil` filenames as before, but also allows it to be set and …
=> Set attachment filename on upload IO

lib/mailgun/address.rb
The Address api currently uses the api_key and host setup on the application configuration. It would be helpful if we could
specify the key and host at runtime.
=> Add option to specify api key and host when initializing Address api
